version: "3.8"

services:
  postgres:
    profiles: ["dev"]
  opensearch:
    profiles: ["dev"]
  opensearch-dash:
    profiles: ["dev"]

  backend:
    environment:
      RUN_MODE: ${RUN_MODE}
      OPENSEARCH_URL: ${OPENSEARCH_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      LLM8B_URL: ${LLM8B_URL}
      LLM70B_URL: ${LLM70B_URL}
      LLM8B_MODEL: ${LLM8B_MODEL}
      LLM70B_MODEL: ${LLM70B_MODEL}
      LLM_API_KEY: ${LLM_API_KEY}

  airflow-webserver:
    environment:
      RUN_MODE: ${RUN_MODE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ORACLE_HOST: ${ORACLE_HOST}
      ORACLE_PORT: ${ORACLE_PORT}
      ORACLE_SERVICE: ${ORACLE_SERVICE}
      ORACLE_USER: ${ORACLE_USER}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      OPENSEARCH_URL: ${OPENSEARCH_URL}

  airflow-scheduler:
    environment:
      RUN_MODE: ${RUN_MODE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ORACLE_HOST: ${ORACLE_HOST}
      ORACLE_PORT: ${ORACLE_PORT}
      ORACLE_SERVICE: ${ORACLE_SERVICE}
      ORACLE_USER: ${ORACLE_USER}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      OPENSEARCH_URL: ${OPENSEARCH_URL}
